### PR TITLE
user login

### PR DESCRIPTION
**Pull request by jonm24**
- added a database function to insert new users into database. returns an error and user object if user already exists.
- added front-end code to store user object in state. 
- refactored other parts of the app to get rid of fake data dependence.
- friends system v1

### CODE REVIEW

**Comment by dwraj** [comment]
Getting error:

Callback URL mismatch.
The provided redirect_uri is not in the list of allowed callback URLs.
Please go to the Application Settings page and make sure you are sending a valid callback url from your application.

When I click 'login' on that inspect link, is this a permissions issue with auth0?

**Comment by jonm24** [comment]
> Getting error:
> 
> 
> 
> Callback URL mismatch.
> 
> The provided redirect_uri is not in the list of allowed callback URLs.
> 
> Please go to the Application Settings page and make sure you are sending a valid callback url from your application.
> 
> 
> 
> When I click 'login' on that inspect link, is this a permissions issue with auth0?

We have to tell auth0 where to redirect back to. we can have a list of links, but rn it's only set to localhost and the vercel URL for the initial auth branch. Once this PR is merged into main we can add the deployment link for main in there too.

**Review by chip-davis — DISMISSED** [review]
looks good king

**Review by MichaelKotwica — APPROVED** [review]
Looks good as the fix is easy!

**Review by Phyotic — APPROVED** [review]

**Pull request merged**
